"""
Tests for scripts/export_site_data.py: the site's data file must be a faithful
export of the model artifacts, with every field the page reads present.

Skipped when artifacts/posterior.nc is absent.
"""

import importlib.util
import json
import os
import re

import numpy as np
import pandas as pd
import pytest

ARTIFACT = "artifacts/posterior.nc"
needs_artifact = pytest.mark.skipif(not os.path.exists(ARTIFACT), reason="run scripts/fit_model.py first")


def _load_export_module():
    spec = importlib.util.spec_from_file_location("export_site_data", "scripts/export_site_data.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


@pytest.fixture(scope="module")
def data():
    return _load_export_module().build()


# Every path the page's logic script reads from window.MMM.
REQUIRED_PATHS = [
    "generated.at", "generated.script", "repo",
    "series.dates", "series.sales", "series.predicted", "series.predLo", "series.predHi", "series.spend",
    "salesStats.mean", "salesStats.min", "salesStats.max", "salesStats.early", "salesStats.late", "salesStats.peakDate", "salesStats.seasonPeakDate", "salesStats.weeks",
    "corr.max", "corr.pair", "lMax", "seed", "seasonAmplitude", "trueParams.tv",
    "channels", "nonMedia", "mediaShare", "trueMediaShare", "params", "recovery.inside", "recovery.total", "recovery.hdiProb",
    "fit.r2", "fit.rmse", "fit.trueNoise", "fit.coverage",
    "sampler.rhat", "sampler.divergences", "sampler.draws", "sampler.pct", "sampler.chains", "sampler.drawsPerChain",
    "sampler.tune", "sampler.targetAccept", "sampler.essBulk", "sampler.essTail", "sampler.seconds",
    "roi", "mroi", "response", "budget", "alloc.ev", "alloc.risk", "equalSplitDelta",
]


def _get(d, path):
    for k in path.split("."):
        d = d[k]
    return d


@needs_artifact
def test_every_field_the_page_reads_is_present(data):
    for p in REQUIRED_PATHS:
        _get(data, p)


@needs_artifact
def test_series_are_the_real_data(data):
    df = pd.read_csv("data/synthetic_weekly.csv")
    assert data["series"]["dates"] == df["date"].tolist()
    np.testing.assert_allclose(data["series"]["sales"], df["sales"], atol=0.5)
    for c in data["series"]["spend"]:
        np.testing.assert_allclose(data["series"]["spend"][c], df[f"spend_{c}"], atol=0.5)
    n = len(df)
    assert len(data["series"]["predicted"]) == len(data["series"]["predLo"]) == len(data["series"]["predHi"]) == n
    assert all(lo <= p <= hi for lo, p, hi in zip(data["series"]["predLo"], data["series"]["predicted"], data["series"]["predHi"]))


@needs_artifact
def test_stats_match_fresh_computation(data):
    df = pd.read_csv("data/synthetic_weekly.csv")
    assert data["salesStats"]["mean"] == round(df["sales"].mean())
    spend = df[[c for c in df if c.startswith("spend_")]]
    corr = spend.corr().to_numpy().copy()
    np.fill_diagonal(corr, 0)
    assert data["corr"]["max"] == round(float(np.abs(corr).max()), 2)


@needs_artifact
def test_recovery_and_diagnostics_match_artifacts(data):
    rec = pd.read_csv("artifacts/parameter_recovery.csv")
    diag = json.load(open("artifacts/diagnostics.json"))
    assert data["recovery"]["inside"] == int(rec["inside_hdi"].sum())
    assert data["recovery"]["total"] == len(rec)
    for _, row in rec.iterrows():
        p = data["params"][row["channel"]][row["param"]]
        assert p["t"] == pytest.approx(row["true"], rel=1e-3)
        assert p["p"] == pytest.approx(row["post_mean"], rel=2e-3)
    assert data["sampler"]["divergences"] == diag["n_divergences"]
    assert data["sampler"]["essBulk"] == round(diag["min_ess_bulk"])
    assert data["sampler"]["draws"] == diag["n_chains"] * diag["n_draws_per_chain"]


@needs_artifact
def test_allocations_sum_to_budget_and_carry_ranges(data):
    channels = [c["key"] for c in data["channels"]]
    for key in ("ev", "risk"):
        a = data["alloc"][key]
        assert sum(a[c] for c in channels) == pytest.approx(data["budget"], abs=len(channels))
        assert a["lo"] <= a["lift"] <= a["hi"]
        assert isinstance(a["precise"], bool)
    assert data["alloc"]["ev"]["precise"] is True
    assert data["equalSplitDelta"] < 0


@needs_artifact
def test_shares_are_consistent(data):
    model_total = sum(c["share"] for c in data["channels"])
    assert model_total == pytest.approx(data["mediaShare"], abs=0.3)
    true_total = sum(c["trueShare"] for c in data["channels"])
    assert true_total == pytest.approx(data["trueMediaShare"], abs=0.3)


@needs_artifact
def test_js_file_is_the_json_plus_header():
    if not os.path.exists("site/mmm-data.js"):
        pytest.skip("run scripts/export_site_data.py first")
    js = open("site/mmm-data.js").read()
    assert js.startswith("/* GENERATED by scripts/export_site_data.py")
    body = re.search(r"window\.MMM = (\{.*\});\n", js, re.S).group(1)
    assert json.loads(body) == json.load(open("site/mmm-data.json"))
    assert js.rstrip().endswith("window.dispatchEvent(new Event('mmm-ready'));")


@needs_artifact
def test_page_reads_only_exported_fields(data):
    """
    Every `M.<a>.<b>` the page logic touches must exist in the exported object.
    This is what stops the page and the exporter drifting apart silently.
    """
    src = open("site/index.dc.html").read()
    used = set(re.findall(r"\bM\.([A-Za-z_][A-Za-z_0-9]*)(?:\.([A-Za-z_][A-Za-z_0-9]*))?", src))
    js_methods = {"map", "filter", "find", "forEach", "slice", "length", "reduce", "sort", "join"}
    missing = []
    for a, b in used:
        if a not in data:
            missing.append(a)
        elif b and b not in js_methods and isinstance(data[a], dict) and b not in data[a]:
            missing.append(f"{a}.{b}")
    assert not missing, f"page reads fields the exporter does not write: {sorted(set(missing))}"
